version: '3.1'

services:
  mariadb:
    image: mariadb:10.11.2-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password123
      MARIADB_DATABASE: prime_holding_app_db
      MARIADB_USER: prime_holding_db_user
      MARIADB_PASSWORD: password123
    ports:
      - 3306:3306

  prime_holding_app:
    image: prime_holding_app:latest
    #restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/prime_holding_app_db?useSSL=false
